### ISSUE TITLE
failed to load source for dependency `cpio-archive`

### ISSUE THREAD

**Issue by nephaste** [johnmave126/extract-samsung-firmware#1]
Hi...

trying to build for Linux ARM64 and intel .. from source but getting error

/build/extract-samsung-firmware# cargo build --release
    Updating git repository `https://github.com/johnmave126/apple-platform-rs.git`
error: failed to get `cpio-archive` as a dependency of package `extract-samsung-firmware v0.1.0 (/build/extract-samsung-firmware)`

Caused by:
  failed to load source for dependency `cpio-archive`

Caused by:
  Unable to update https://github.com/johnmave126/apple-platform-rs.git#0680640a

Caused by:
  failed to clone into: /root/.cargo/git/db/apple-platform-rs-33216a0a4c335e44

Caused by:
  failed to authenticate when downloading repository

  * attempted to find username/password via git's `credential.helper` support, but failed

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to acquire username/password from local configuration

how can fix it ? please

![image](https://github.com/johnmave126/extract-samsung-firmware/assets/3392684/904ea569-d82b-4d6b-917c-0d1e9ddeddc7)

**Comment by johnmave126** [comment]
Oh, I forgot to update Cargo.toml after a patch was accepted upstream. Will fix that now.

**Comment by nephaste** [comment]
thanks a lot

**Comment by johnmave126** [comment]
> thanks a lot

Please try again and see whether it has been fixed.

**Comment by nephaste** [comment]
works fine... i will push your project as a package for Qnap NAS Community ( www.myqnap.org)

![image](https://github.com/johnmave126/extract-samsung-firmware/assets/3392684/05517c83-9464-47bb-86c5-8b62a4c8345d)

**Comment by johnmave126** [comment]
Closed with c6545e978dc53b03b69fb606d2b809482eb5c771
